Repository qlcchain/go-qlc, pull requests merged in 2019-10, with the labels that each got.

#632 refactor: Dockefile and docker-compose
  .dockerignore
  .github/workflows/go.yml
  .github/workflows/stale.yml
  .github/workflows/welcome.yml
  .gitignore
  .golangci.yml
  .mergify.yml
  Makefile
  README.md
  common/event/event_bus.go
  common/event/event_bus_impl.go
  common/event/event_handlers.go
  consensus/dpos/dpos_impl.go
  consensus/pov/pov_processor.go
  consensus/pov/pov_sync.go
  consensus/receiver.go
  docker/Dockerfile
  docker/Dockerfile_builder
  docker/data/.gitkeep
  docker/docker-compose.yml
  docker/docker_push.sh
  docker/entrypoint.sh
  ledger/relation/relation_impl.go
  p2p/qlcService.go
Labels: ready-to-rebase-and-merge

#640 fix: only one gorouting can handle the pullrequest at the same time
  ledger/ledger_dump_test.go
  p2p/messageMonitor.go
  p2p/sync.go
Labels: ready-to-merge

#644 fix: add testcase for gap pov interfaces
  common/types/unchecked.go
  consensus/dpos/dpos_impl.go
  ledger/ledger_uncheck.go
  ledger/ledger_uncheck_test.go
  rpc/api/debug.go
Labels: ready-to-rebase-and-merge

#645 fix: delete netAttribute
  p2p/node.go
  p2p/node_test.go
  p2p/stream.go
  p2p/streamManager.go
Labels: ready-to-merge

#646 test: add pov sync testcase
  cmd/client/commands/pov.go
  cmd/client/commands/pov_blockinfo.go
  cmd/client/commands/tx.go
  cmd/client/commands/tx_blockinfo.go
  consensus/pov/pov_chain.go
  consensus/pov/pov_pow.go
  consensus/pov/pov_sync_peer.go
  consensus/pov/pov_sync_test.go
  mock/mock_pov.go
Labels: Type: Maintenance

#650 feat: check contract receive block pending
  .goreleaser.yml
  Makefile
  chain/autoreceive_service.go
  chain/consensus_service.go
  chain/context/chain_context_test.go
  chain/version/version.go
  chain/version/version_test.go
  cmd/client/commands/version.go
  cmd/server/commands/root.go
  cmd/server/commands/version.go
  ledger/db/badger_impl.go
  ledger/db/dbstore.go
  ledger/ledger.go
  ledger/process/cache_processor.go
  ledger/process/ledger_processor.go
  rpc/api/chain.go
  rpc/api/ledger.go
  rpc/apis.go
Labels: ready-to-rebase-and-merge

#651 feat: add pov height to block
  ledger/ledger.go
  mock/mock_pov.go
  rpc/api/black_hole.go
  rpc/api/ledger.go
  rpc/api/ledger_test.go
  rpc/api/mintage.go
  rpc/api/nep5_pledge.go
  rpc/api/rewards.go
  rpc/api/rewards_test.go
  rpc/apis.go
  test/generate_chain.go
Labels: ready-to-rebase-and-merge

#652 feat: optimize pov mining & debug info
  cmd/client/commands/debug.go
  cmd/client/commands/debug_povinfo.go
  cmd/client/commands/pov_mininginfo.go
  cmd/client/commands/root.go
  cmd/client/commands/version.go
  cmd/server/commands/root.go
  cmd/server/commands/version.go
  consensus/pov/consensus_pov.go
  consensus/pov/pov_chain.go
  consensus/pov/pov_chain_test.go
  consensus/pov/pov_fake.go
  consensus/pov/pov_impl.go
  consensus/pov/pov_pow.go
  consensus/pov/pov_processor.go
  consensus/pov/pov_sync.go
  consensus/pov/pov_sync_pool.go
  consensus/pov/pov_txpool.go
  ledger/db/badger_impl.go
  ledger/process/ledger_processor.go
  miner/pov_worker.go
  mock/mock_pov.go
  p2p/node.go
  p2p/node_test.go
  p2p/stream.go
  rpc/api/debug.go
  rpc/api/pov.go
  trie/node_pool.go
Labels: Priority: Medium, Type: Enhancement, ready-to-rebase-and-merge

#653 fix: rollback cache account
  ledger/process/rollback.go
  ledger/process/rollback_test.go
Labels: ready-to-rebase-and-merge

#654 feat: add more pov sync debug info
  consensus/pov/pov_sync.go
  consensus/pov/pov_sync_peer.go
  consensus/pov/pov_sync_pool.go
Labels: ready-to-merge

#655 fix: change reward contract data
  cmd/client/commands/miner_reward.go
  cmd/client/commands/rep_reward.go
  consensus/dpos/dpos_impl.go
  consensus/dpos/online.go
  consensus/dpos/processor.go
  ledger/ledger_pov.go
  rpc/api/miner.go
  rpc/api/pov.go
  rpc/api/representative.go
  vm/contract/abi/abi_miner.go
  vm/contract/abi/abi_representative.go
  vm/contract/miner.go
  vm/contract/representative.go
Labels: ready-to-rebase-and-merge

#658 fix: optimize pov tx pending check
  common/params_pov.go
  common/params_pov_testnet.go
  common/types/block_pov.go
  consensus/pov/pov_chain.go
  consensus/pov/pov_chain_test.go
  consensus/pov/pov_processor.go
  consensus/pov/pov_processor_test.go
  consensus/pov/pov_sync.go
  consensus/pov/pov_sync_pool.go
  consensus/pov/pov_sync_test.go
  consensus/pov/pov_verifier.go
Labels: ready-to-merge

#657 fix: pack/unpack balance
  vm/abi/argument.go
  vm/abi/pack.go
  vm/abi/pack_test.go
  vm/abi/type.go
  vm/abi/type_test.go
  vm/abi/unpack.go
  vm/abi/unpack_test.go
  vm/contract/blackhole_test.go
Labels: ready-to-merge

#660 Fix/cons optimize
  consensus/dpos/dpos_impl.go
  consensus/dpos/processor.go
  ledger/ledger.go
  vm/contract/abi/abi_miner_test.go
  vm/contract/abi/abi_reoresentative_test.go
Labels: ready-to-rebase-and-merge

#668 feat: add pov pubsub for new blocks
  consensus/pov/pov_sync.go
  consensus/pov/pov_sync_pool.go
  rpc/api/pov.go
  rpc/api/pov_pubsub.go
  rpc/api/pov_test.go
Labels: ready-to-merge

#669 fix: resend block in the blockcache
  p2p/messageMonitor.go
  p2p/node.go
Labels: ready-to-rebase-and-merge

#674 feat: add contract describe
  ledger/process/ledger_processor.go
  vm/contract/blackhole.go
  vm/contract/contract.go
  vm/contract/miner.go
  vm/contract/mintage.go
  vm/contract/nep5_pledge.go
  vm/contract/representative.go
  vm/contract/rewards.go
Labels: ready-to-merge

#675 refactor: pledge cmds
  cmd/client/commands/miner_reward.go
  cmd/client/commands/pledge.go
  cmd/client/commands/pledge_pledge.go
  cmd/client/commands/pledge_recvpend.go
  cmd/client/commands/pledge_withdraw.go
  cmd/client/commands/rep_reward.go
  cmd/client/commands/root.go
  cmd/client/commands/withdraw_pledge.go
  rpc/api/nep5_pledge.go
Labels: ready-to-merge

#676 feat: add cache memory to ledger
  cmd/client/commands/dump_ledger.go
  cmd/client/commands/ledger.go
  cmd/client/commands/ledger_dump.go
  cmd/client/commands/ledger_gc.go
  cmd/client/commands/root.go
  ledger/ledger.go
  ledger/ledger_account.go
  ledger/ledger_account_cache.go
  ledger/ledger_account_test.go
  ledger/ledger_block.go
  ledger/ledger_block_cache.go
  ledger/ledger_block_test.go
  ledger/ledger_cache.go
  ledger/ledger_dump.go
  ledger/ledger_pending.go
  ledger/ledger_pending_cache.go
  ledger/ledger_pending_test.go
  rpc/api/debug.go
  rpc/api/ledger.go
Labels: ready-to-rebase-and-merge

#677 fix: confirm-chain process may exit abnormally
  consensus/dpos/processor.go
Labels: ready-to-rebase-and-merge

#679 feat: add ascii logo
  chain/version/version.go
  chain/version/version_test.go
  cmd/client/commands/pledge_withdraw.go
  cmd/main.go
  cmd/server/commands/root.go
Labels: ready-to-merge

#681 fix: can not update contract reward block data
  ledger/process/sync_processor.go
Labels: ready-to-merge

#683 chore: golangci lint consensus pov
  consensus/pov/pov_chain.go
  consensus/pov/pov_chain_test.go
  consensus/pov/pov_event.go
  consensus/pov/pov_impl.go
  consensus/pov/pov_pow.go
  consensus/pov/pov_processor.go
  consensus/pov/pov_processor_test.go
  consensus/pov/pov_state.go
  consensus/pov/pov_sync.go
  consensus/pov/pov_sync_peer.go
  consensus/pov/pov_sync_pool.go
  consensus/pov/pov_sync_test.go
  consensus/pov/pov_txpool.go
  consensus/pov/pov_txpool_test.go
  consensus/pov/pov_verifier.go
  consensus/pov/pov_verifier_test.go
Labels: ready-to-merge

#684 feat: add pub/sub debug interface
  rpc/api/debug.go
  rpc/api/ledger.go
  rpc/api/subscribe.go
Labels: ready-to-merge

#682 refactor: log service to support hot deployment
  chain/chainmanager_service.go
  chain/chainmanager_service_test.go
  chain/context/chain_context.go
  chain/context/chain_context_test.go
  chain/helper.go
  chain/log_service.go
  cmd/main.go
  cmd/server/commands/root.go
  config/config_manager.go
  config/config_manager_test.go
  log/logger.go
  log/logger_debug.go
  log/logger_test.go
  rpc/api/config_test.go
  rpc/rpc.go
Labels: ready-to-merge

#687 fix: pubsub channel blocked
  rpc/api/ledger.go
  rpc/api/pov.go
  rpc/api/pov_pubsub.go
  rpc/api/subscribe.go
Labels: ready-to-merge

#688 fix: pov should check confirmed state blocks
  consensus/pov/pov_chain.go
  consensus/pov/pov_processor.go
  consensus/pov/pov_sync_pool.go
  consensus/pov/pov_txpool.go
  consensus/pov/pov_verifier.go
  ledger/ledgerstore.go
  rpc/api/pov.go
Labels: ready-to-merge

#689 fix: process syncronized blocks while pulling
  consensus/dpos/processor.go
Labels: ready-to-rebase-and-merge
