Repository qlcchain/go-qlc, pull requests merged in 2020-07, with the labels that each got.

#1160 test: fix dpos unit test issue
  consensus/dpos/cache_test.go
  consensus/dpos/dpos_impl.go
  consensus/dpos/dpos_impl_testnet.go
  consensus/dpos/dpos_integration_test.go
  consensus/dpos/dpos_test.go
  consensus/dpos/online.go
Labels: ready-to-rebase-and-merge

#1161 test: enable ledger test cases for both main net and test net
  rpc/api/ledger_default_test.go
  rpc/api/ledger_test.go
  rpc/api/ledger_testnet_test.go
Labels: ready-to-rebase-and-merge

#1162 fix: peer statistics bug
  p2p/node.go
Labels: ready-to-merge

#1174 hotfix: delete the cache block instantly can cause high disk usage
  ledger/ledger.go
Labels: ready-to-rebase-and-merge

#1175 refactor: call method to add confirmed block
  consensus/dpos/dpos_impl.go
  consensus/dpos/dpos_impl_testnet.go
  ledger/ledger_block.go
Labels: ready-to-merge

#1177 fix: pov tx count
  ledger/ledger_pov.go
  ledger/ledger_pov_test.go
  mock/mocks/store.go
  rpc/api/pov.go
Labels: ready-to-rebase-and-merge

#1181 chore(deps): bump github.com/awnumar/memguard from 0.16.2 to 0.22.2
  go.mod
  go.sum
Labels: ready-to-rebase-and-merge

#1184 test: refactor p2p test cases(#1158)
  p2p/message_test.go
  p2p/node_test.go
Labels: Priority: Medium, ready-to-merge

#1190 feat: upgrade badger db to v2.0 coexist with v1.6 library
  common/storage/db/migration/migration.go
  common/storage/db/migration/migration_test.go
  go.mod
  go.sum
Labels: ready-to-merge

#1192 feat: set testnet miner pledge to 0
  common/params_pov_testnet.go
Labels: ready-to-merge

#1199 fix: upgrade ledger to reset pending infos
  common/storage/storage.go
  ledger/ledger.go
  ledger/ledger_pending.go
  ledger/migration/migration.go
  ledger/migration/migration_test.go
  rpc/api/ledger_test.go
  rpc/grpc/apis/ledger_test.go
Labels: ready-to-rebase-and-merge

#1201 fix: remove nep5 contract pending data
  cmd/client/commands/kyc_admin_update.go
  cmd/client/commands/kyc_operator_update.go
  cmd/client/commands/kyc_status_update.go
  cmd/client/commands/kyc_trade_address_update.go
  consensus/dpos/dpos_impl_testnet_test.go
  ledger/migration/migration.go
  p2p/node_test.go
  rpc/api/kyc.go
  rpc/api/kyc_test.go
  rpc/api/ledger_default_test.go
  rpc/api/ledger_testnet_test.go
  rpc/api/pov_pubsub.go
  vm/contract/abi/abi_kyc.go
  vm/contract/abi/abi_kyc_test.go
  vm/contract/abi/abi_kyc_types.go
  vm/contract/kyc.go
  vm/contract/kyc_test.go
  vm/contract/nep5_pledge.go
  vm/contract/nep5_pledge_test.go
Labels: ready-to-rebase-and-merge
