Repository qlcchain/go-qlc, pull requests merged in 2020-05, with the labels that each got.

#1096 fix: ptmkey contract checkContractSendBlock failed
  vm/contract/contract.go
  vm/contract/ptmkey.go
Labels: Priority: Critical, ready-to-merge

#1106 feat:add ptmkey new btypes {a2p,dod,cloud}
  common/contract.go
  common/contract_test.go
  privacy/client.go
  vm/contract/abi/abi_ptmkey.go
  vm/contract/abi/abi_ptmkey_test.go
  vm/contract/ptmkey.go
  vm/contract/ptmkey_test.go
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#1110 fix: move privacy config to v7
  chain/permission_service.go
  config/config_v6.go
  config/config_v7.go
  config/migration_v5_v6.go
  config/migration_v6_v7.go
  consensus/dpos/dpos_impl.go
  consensus/dpos/processor.go
  consensus/pov/pov_state.go
  ledger/ledger_vm_store_test.go
  ledger/relation/db/sqlite.go
  rpc/api/ptmkey_test.go
  vm/contract/abi/abi_ptmkey.go
Labels: ready-to-merge

#1115 feat: use peerid instead of ip + port to reject node connection
  go.mod
  go.sum
  p2p/connectionGater.go
  p2p/connectionGater_test.go
  p2p/node.go
  p2p/protector.go
  p2p/qlcService.go
Labels: ready-to-merge

#1119 feat: dod settlement smart contract
  cmd/client/commands/dod_settlement.go
  cmd/client/commands/dod_settlement_change_order.go
  cmd/client/commands/dod_settlement_change_response.go
  cmd/client/commands/dod_settlement_create_order.go
  cmd/client/commands/dod_settlement_create_response.go
  cmd/client/commands/dod_settlement_resource_ready.go
  cmd/client/commands/dod_settlement_terminate_order.go
  cmd/client/commands/dod_settlement_terminate_response.go
  cmd/client/commands/dod_settlement_update_order_info.go
  cmd/client/commands/dod_settlement_update_response.go
  cmd/client/commands/root.go
  common/contract.go
  common/storage/storage.go
  common/types/unchecked.go
  common/vmcontract/contractaddress/address.go
  consensus/dpos/dpos_impl.go
  consensus/dpos/processor.go
  go.mod
  go.sum
  ledger/ledger_uncheck.go
  ledger/ledger_uncheck_test.go
  ledger/process/ledger_check.go
  ledger/process/verifier.go
  mock/mocks/store.go
  rpc/api/contract.go
  rpc/api/dod_settlement.go
  rpc/api/dod_settlement_test.go
  rpc/apis.go
  vm/contract/abi/abi_dod_settlement.go
  vm/contract/abi/abi_dod_settlement_test.go
  vm/contract/abi/abi_dod_settlement_types.go
  vm/contract/abi/abi_dod_settlement_types_enum.go
  vm/contract/abi/abi_dod_settlement_types_enum_test.go
  vm/contract/abi/abi_dod_settlement_types_gen.go
  vm/contract/abi/abi_dod_settlement_types_gen_test.go
  vm/contract/abi/abi_dod_settlement_types_test.go
  vm/contract/contract.go
  vm/contract/dod_settlement.go
  vm/contract/dod_settlement_test.go
Labels: Priority: High, ready-to-rebase-and-merge

#1120 feat: add dod order rpc interfaces
  rpc/api/dod_settlement.go
  rpc/api/dod_settlement_test.go
Labels: ready-to-rebase-and-merge
