Repository qlcchain/go-qlc, pull requests merged in 2020-06, with the labels that each got.

#1124 feat: dod settlement rpc patch
  cmd/client/commands/dod_settlement_change_order.go
  cmd/client/commands/dod_settlement_create_order.go
  rpc/api/dod_settlement.go
  rpc/api/dod_settlement_test.go
  vm/contract/abi/abi_dod_settlement.go
  vm/contract/abi/abi_dod_settlement_test.go
  vm/contract/abi/abi_dod_settlement_types.go
  vm/contract/abi/abi_dod_settlement_types_gen.go
  vm/contract/abi/abi_dod_settlement_types_gen_test.go
  vm/contract/abi/abi_dod_settlement_types_test.go
  vm/contract/dod_settlement.go
  vm/contract/dod_settlement_test.go
Labels: Type: Enhancement, ready-to-rebase-and-merge

#1125 fix: add more dod settlement validation check
  rpc/api/dod_settlement.go
  rpc/api/dod_settlement_test.go
  vm/contract/abi/abi_dod_settlement.go
  vm/contract/abi/abi_dod_settlement_test.go
  vm/contract/abi/abi_dod_settlement_types.go
  vm/contract/abi/abi_dod_settlement_types_gen.go
  vm/contract/abi/abi_dod_settlement_types_test.go
  vm/contract/dod_settlement.go
  vm/contract/dod_settlement_test.go
Labels: Type: Enhancement, ready-to-rebase-and-merge

#1131 feat: adjust vm log print
  vm/vmstore/vm_store.go
Labels: ready-to-merge

#1133 feat: dod settlement privacy
  cmd/client/commands/dod_settlement_change_order.go
  cmd/client/commands/dod_settlement_change_response.go
  cmd/client/commands/dod_settlement_create_order.go
  cmd/client/commands/dod_settlement_create_response.go
  cmd/client/commands/dod_settlement_terminate_order.go
  cmd/client/commands/dod_settlement_terminate_response.go
  cmd/client/commands/dod_settlement_update_order_info.go
  cmd/client/commands/dod_settlement_update_product_info.go
  cmd/client/commands/dod_settlement_update_response.go
  consensus/dpos/dpos_impl.go
  consensus/dpos/dpos_impl_test.go
  consensus/pov/pov_state.go
  ledger/ledger_block.go
  ledger/process/ledger_check.go
  ledger/process/ledger_processor.go
  rpc/api/contract.go
  vm/contract/dod_settlement.go
Labels: Type: Enhancement, ready-to-rebase-and-merge

#1134 feat: add rpc getInternalIdByOrderId
  rpc/api/dod_settlement.go
  rpc/api/dod_settlement_test.go
  vm/contract/abi/abi_dod_settlement_types.go
Labels: ready-to-rebase-and-merge

#1137 fix: optimize dod settlement invoice
  vm/contract/abi/abi_dod_settlement.go
  vm/contract/abi/abi_dod_settlement_test.go
  vm/contract/abi/abi_dod_settlement_types.go
Labels: ready-to-rebase-and-merge

#1138 fix: permission service auto add node issue
  chain/permission_service.go
Labels: ready-to-rebase-and-merge

#1141 fix: when getting onlineinfo, own ip is incorrect
  p2p/node.go
Labels: ready-to-merge

#1150 feat: upgrade badger to v2.0
  common/storage/db/badger.go
  common/storage/db/badger_test.go
  common/storage/db/migration/migration.go
  common/storage/db/migration/migration_test.go
  go.mod
  go.sum
Labels: ready-to-rebase-and-merge

#1157 refactor: move dod settlement contract api to enterprise build
  cmd/client/commands/dod_settlement.go
  cmd/client/commands/dod_settlement_change_order.go
  cmd/client/commands/dod_settlement_change_response.go
  cmd/client/commands/dod_settlement_create_order.go
  cmd/client/commands/dod_settlement_create_response.go
  cmd/client/commands/dod_settlement_terminate_order.go
  cmd/client/commands/dod_settlement_terminate_response.go
  cmd/client/commands/dod_settlement_update_order_info.go
  cmd/client/commands/dod_settlement_update_product_info.go
  cmd/client/commands/dod_settlement_update_response.go
  cmd/client/commands/helper.go
  cmd/client/commands/helper_testnet.go
  cmd/client/commands/root.go
  config/config_v8.go
  config/migration_v7_v8.go
  rpc/api/dod_settlement.go
  rpc/api/dod_settlement_test.go
  rpc/grpc/apis/dod_settlement.go
  rpc/grpc/apis/dod_settlement_test.go
  rpc/grpc/server/server.go
Labels: ready-to-merge

#1159 fix: update libp2p package and fix the dht bug
  go.mod
  go.sum
  p2p/node.go
Labels: ready-to-merge
