Repository qlcchain/go-qlc, pull requests merged in 2020-04, with the labels that each got.

#1046 feat: refactor relational table schema
  common/storage/relationdb/mysql.go
  common/storage/relationdb/pgsql.go
  common/storage/relationdb/relation.go
  common/storage/relationdb/sqlite.go
  common/storage/relationdb/sqlite_test.go
  common/types/block_state.go
  common/types/block_state_test.go
  common/types/interface.go
  common/types/schema.go
  ledger/cache.go
  ledger/ledger.go
  ledger/ledger_generic.go
  ledger/process/ledger_processor.go
  ledger/relation/db/mysql.go
  ledger/relation/db/relation.go
  ledger/relation/db/sqlite.go
  ledger/relation/db/sqlite_test.go
  ledger/relation/interface.go
  ledger/relation/relation_impl.go
  ledger/relation/relation_impl_test.go
  ledger/relation/relation_manage.go
  ledger/relation/relation_manage_test.go
  ledger/relation/schema.go
Labels: ready-to-rebase-and-merge

#1047 fix: method handler crashed when size<count
  rpc/api/net.go
  rpc/api/net_test.go
Labels: ready-to-merge

#1048 feat: support batch upload CDR records
  .github/workflows/reviewdog.yml
  ledger/cache.go
  rpc/api/settlement.go
  rpc/api/settlement_test.go
  vm/contract/abi/abi_settlement.go
  vm/contract/abi/abi_settlement_gen.go
  vm/contract/abi/abi_settlement_gen_test.go
  vm/contract/abi/abi_settlement_test.go
  vm/contract/settlement.go
  vm/contract/settlement_test.go
Labels: ready-to-merge

#1050 feat: p2p module integrated permission mechanism
  common/contract.go
  common/topic/messages.go
  common/vmcontract/contract.go
  config/config_v2.go
  config/config_v2_default.go
  config/config_v2_testnet.go
  consensus/dpos/dpos_impl.go
  ledger/cache.go
  p2p/node.go
  p2p/protector.go
  p2p/protector_test.go
  p2p/qlcService.go
  rpc/api/miner.go
  rpc/api/miner_test.go
  rpc/api/public_key_distribution.go
  rpc/api/public_key_distribution_test.go
  rpc/api/representative.go
  rpc/api/representative_test.go
  vm/contract/contract.go
  vm/contract/permission.go
  vm/contract/permission_test.go
  vm/contract/settlement.go
Labels: ready-to-merge

#1063 fix: reduplicate tx
  ledger/relation/relation_impl.go
Labels: ready-to-merge

#1064 feat: add privacy base framework
  chain/context/chain_context.go
  chain/helper.go
  chain/privacy_service.go
  chain/privacy_service_test.go
  cmd/client/commands/privacy.go
  cmd/client/commands/privacy_demokv.go
  cmd/client/commands/privacy_payload.go
  cmd/client/commands/root.go
  common/storage/storage.go
  common/topic/messages.go
  common/topic/topic.go
  common/types/block_state.go
  common/types/block_state_gen.go
  common/types/block_state_test.go
  common/util/util.go
  common/util/util_test.go
  common/vmcontract/chaincontract/contract.go
  common/vmcontract/contractaddress/address.go
  config/config_v6.go
  config/migration_v5_v6.go
  consensus/dpos/dpos_impl.go
  consensus/dpos/processor.go
  consensus/pov/pov_state.go
  ledger/ledger_block.go
  ledger/ledger_privacy.go
  ledger/ledger_privacy_test.go
  ledger/ledger_sync.go
  ledger/ledger_uncheck.go
  ledger/ledgerstore.go
  ledger/process/ledger_check.go
  ledger/process/ledger_processor.go
  ledger/process/rollback.go
  mock/mocks/store.go
  p2p/protector_test.go
  privacy/client.go
  privacy/http.go
  privacy/privacy.go
  privacy/privacy_test.go
  privacy/ptm.go
  privacy/unix.go
  privacy/unix_test.go
  rpc/api/contract.go
  rpc/api/contract_test.go
  rpc/api/contract_testnet_test.go
  rpc/api/ledger_test.go
  rpc/api/privacy.go
  rpc/api/privacy_test.go
  rpc/apis.go
  vm/contract/abi/abi_privacy_demokv.go
  vm/contract/privacy_demokv.go
  vm/contract/privacy_demokv_testnet.go
Labels: ready-to-merge

#1066 feat: block check indicate specific error message
  consensus/dpos/dpos_test.go
  consensus/dpos/processor.go
  ledger/ledger_test.go
  ledger/process/cache_processor.go
  ledger/process/cache_processor_test.go
  ledger/process/ledger_check.go
  ledger/process/ledger_processor.go
  ledger/process/ledger_processor_test.go
  rpc/api/ledger.go
Labels: ready-to-merge

#1070 refactor: p2p pubsub using the latest libp2p package
  p2p/node.go
  p2p/pubsub/publisher.go
  p2p/pubsub/subscriber.go
  p2p/pubsub/topic.go
  p2p/streamManager.go
Labels: ready-to-merge

#1072 refactor: bootNode config
  chain/bootnode_http_service.go
  chain/bootnode_http_service_test.go
  config/config_v2.go
  config/config_v2_default.go
  config/config_v2_testnet.go
  config/defaults_net.go
  config/defaults_testnet.go
  config/migration_v5_v6.go
  p2p/discovery_test.go
  p2p/messageMonitor_test.go
  p2p/node.go
  p2p/streamManager_test.go
  p2p/sync_test.go
Labels: ready-to-merge

#1091 feat: add permission service to add preconfigured nodes automatically
  chain/context/chain_context.go
  chain/helper.go
  chain/permission_service.go
  chain/permission_service_test.go
  config/config.go
  config/config_test.go
  config/config_v2.go
  config/config_v2_default.go
  config/config_v2_testnet.go
  config/config_v7.go
  config/defaults_net.go
  config/defaults_testnet.go
  config/genesis_test.go
  config/genesis_testnet_test.go
  config/migration_v5_v6.go
  config/migration_v6_v7.go
  config/migration_v6_v7_test.go
  config/migration_v6_v7_testnet_test.go
  ledger/process/ledger_processor.go
  ledger/process/ledger_processor_test.go
  p2p/node.go
  p2p/protector_test.go
  p2p/qlcService.go
  rpc/api/ledger.go
Labels: ready-to-rebase-and-merge

#1090 feat: add an rpc interface to query the peerid of node
  rpc/api/net.go
  rpc/api/net_test.go
Labels: ready-to-merge

#1093 feat: Increase ptmkey contract unit test coverage(#1087)
  cmd/client/commands/ptmkey.go
  cmd/client/commands/ptmkey_getpubkey.go
  cmd/client/commands/ptmkey_pkdelete.go
  cmd/client/commands/ptmkey_pkupdate.go
  cmd/client/commands/root.go
  common/contract.go
  common/contract_test.go
  common/vmcontract/contractaddress/address.go
  rpc/api/ptmkey.go
  rpc/api/ptmkey_test.go
  rpc/apis.go
  vm/contract/abi/abi_ptmkey.go
  vm/contract/abi/abi_ptmkey_test.go
  vm/contract/ptmkey.go
  vm/contract/ptmkey_test.go
Labels: Priority: Medium, Status: Available, ready-to-merge

#1094 test: add vm store test cases
  vm/vmstore/vm_store.go
  vm/vmstore/vm_store_test.go
Labels: ready-to-merge

#1095 feat: relation register should be slice
  ledger/ledger.go
  ledger/ledger_relation_test.go
Labels: ready-to-merge
